### ISSUE TITLE
Crash On A Specific game

### ISSUE THREAD

**Issue by ghost** [Polarmods/PolarImGui#2]
the game crashes in emulator when entering the game on a real device it produces an auto shot (automatic shot) do you know how to fix it?

stacktrace : 

![image](https://user-images.githubusercontent.com/81579523/175175635-cc39f09d-9cba-4019-bf69-d7e9be6512ed.png)

**Comment by Rev** [comment]
What game? This could be caused by the register natives hook. Could you comment it out in the native-lib.cpp, and let me know if that fixes the issue?

**Comment by IRCKALUS** [comment]
nombre del juego : standoff 2

**Comment by IRCKALUS** [comment]
All are working i fixed myself the problem.

**Comment by IRCKALUS** [comment]
> kid, first stop helping pasha production and others leech stuff from standoff 2 like token authorization and others, fix it urself lol

First of all i know about "IRC" i am IRCKALUS no IRC

**Comment by Rev** [comment]
Well, for anyone reading this in the future in case they get the same issue, you have a few options.

1) I believe houdini just translates ARM instructions to x86 (x86 is what 32-bit Android emulators typically use), so running the game on a device that directly uses an ARM cpu would fix the issue (as it wouldn't need libhoudini.so to translate the instructions).

2) Find a way to hook it without it crashing, as, without it, you won't be receiving touch input.

3) Find another way to receive inputs, such as through using View.OnTouchListener, but using it would be quite primitive in this case.
