### ISSUE TITLE
Touch Fucks Up

### ISSUE THREAD

**Issue by chr1srbx** [Polarmods/PolarImGui#3]
Tocuh breaks if screenscale is changed(isn't the original resolution).

**Comment by Rev** [comment]
There are different ways you could fix this yourself.

1) Use GLSurfaceView to render the menu; https://developer.android.com/reference/android/opengl/GLSurfaceView
2) Use internal Unity functions to get touch input, such as get_position in the Touch class, and GetTouch/get_touchCount in the Input class.
3) Set the resolution of the application to your screens resolution. Most Unity applications have SetResolution in the Screen class, which can be used to do this.
